### ISSUE TITLE
Add custom wordlist(s) option

### ISSUE THREAD

**Issue by nitz** [cmdwtf/KeePassDiceware#1]
In addition to the embedded dictionaries, it would be nice to allow users to provide their own wordlist(s).

(req. from rimfire)

**Comment by SecurityCze** [comment]
Hello,
are you looking for a help with this feature?

This is a feature I am currently missing. So maybe I can help. I just do not want to start working on it, if you already have something in the works / want to implement it yourself.

### If you would like me to try and implement this:
Do you have any plan as to how to implement it?

1. The obvious way would be to repeat what you did with salt selection.
However I am not a big fan of `DataGridView`. It might be a bit ugly. Not sure if it would be possible to keep the categories.
It might look similar to this:
![wordlist_same_as_salt](https://github.com/user-attachments/assets/a12dba1b-ee13-4381-9db4-9f3cd5afd42a)

2. Keep the `ListView` and add a category "Custom".
Then we would need a way to modify those custom dictionaries. Perhaps a button "Configure custom dictionaries" that would open a dialog that would look something like this (its only purpose would be to add and remove custom dictionaries):
> ![wordlist_keep_current_selection](https://i.ytimg.com/vi/PAk31IekYj4/maxresdefault.jpg)
> Random screenshot from [this video](https://m.youtube.com/watch?v=PAk31IekYj4) that illustrates what I am talking about.

Any input on how do you want it to look?

**Comment by nitz** [comment]
I definitely haven't started on it at all, so you are more than welcome to take a crack at it. I very much appreciate all the effort you've put into it recently :)

Okay, so the categories were more of a "means to an end" than anything else. I was very intentionally lifting a lot of the "style" from the Strongbox implementation, since that was what inspired me in the first place. By no means to they need to stay. I certainly would appreciate uniformity with the salt dialog, but I don't think it's a showstopper if it's not.

My general theory is this: A person who is using KeePass in the first place, and has cared enough to extend its functionality with a plugin, is likely resourceful enough to be able to handle complex and varying dialogs.

I think it boils down to this:

I love very much that you've offered to take this on, as I know it would make many people quite happy to see it implemented. Please feel free to implement it in the way that feels comfortable to you, and we can iron out anything that might arise later. I've found that works quite well as a methodology with tiny projects like this: Implement the happy path, and the rest will follow!

**Comment by SecurityCze** [comment]
No worries, I have been quite enjoying my work here. Always happy to help.

I started on the implementation in [my branch](https://github.com/SecurityCze/KeePassDiceware/tree/custom_wordlist). It is just a start as of now. And unfortunately I will not have a lot of time in the next few weeks.

So for now I have a sneak peak on how it looks like so for:
![image](https://github.com/user-attachments/assets/1926e150-0f57-4ad2-b409-c1d9975549f3)

![image](https://github.com/user-attachments/assets/997c8a48-2ac6-4a58-bb07-e36af9274477)

**Comment by SecurityCze** [comment]
Ok, almost done.

When you have a moment: could you take a look at it [(my custom_wordlist branch)](https://github.com/SecurityCze/KeePassDiceware/tree/custom_wordlist), and let me know what do you think?

### TODO:

- [ ] Settings migration - not tested, probably completely broken
- [ ] Tab order in forms - probably need polish, mostly random now
- [ ] User ordering of wordlists?
- [ ] Other?

But other than that - it should be good to go!

### Current state:
---
Options form:
![image](https://github.com/user-attachments/assets/840bd4dc-e05b-4de2-a864-e11659037969)

---
Word list form:
![image](https://github.com/user-attachments/assets/f1b2795f-1c6c-437f-9f2b-1092ccedd1b9)

- You can enable, disable, and delete (by selecting a row by clicking on left margin and pressing a delete) all wordlists. 
- You can add custom wordlist by clicking `Add` button. A File dialog is opened where you can select your own.
- You can change name of custom wordlist by double clicking it.
- You can change path to custom wordlist by double clicking it.

I originally wanted to keep the "Click on the last empty row to create a new one" mechanic. However I got stuck how to easily let user pick a path. So I created the `Add` button.

**Comment by nitz** [comment]
I am absolutely loving this!

I don't think ordering lists is super important. I have a feeling this is the sort of thing most users that will make use of it, will set once and leave it. I think it's perfectly fine to punt on that until it seems absolutely necessary for something.

> I originally wanted to keep the "Click on the last empty row to create a new one" mechanic. However I got stuck how to easily let user pick a path. So I created the `Add` button.

100% acceptable, data grids are sometimes just more headache than they're worth 😂

**Comment by SecurityCze** [comment]
Thank you for your feedback. You are right. I did not waste any more time with column ordering. While it might be nice, it is definitely not needed (especially when you can remove rows to only keep the few actually usable for you).

I also did not add any additional functionality. Just finished tab orders and config migration.

Any feedback and (especially) testing is welcome.
